//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Inactive { get; set; }
        public string Name { get; set; }
        public string Display_Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string MAS_Vendor_Code { get; set; }
        public Nullable<double> Base_Price { get; set; }
        public string External_ID { get; set; }
        public double Internal_ID { get; set; }
        public string Purchase_Price { get; set; }
        public string Vendor_Code { get; set; }
        public int Id { get; set; }
    }
}
