//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_COOKED
    {
        public string externalid { get; set; }
        public string tranId { get; set; }
        public string Customer { get; set; }
        public string trandate { get; set; }
        public string orderstatus { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string otherrefnum { get; set; }
        public string memo { get; set; }
        public string salesrep { get; set; }
        public string opportunity { get; set; }
        public string saleseffectivedate { get; set; }
        public string leadsource { get; set; }
        public string partner { get; set; }
        public string Department { get; set; }
        public string Class { get; set; }
        public string Location { get; set; }
        public string couponcode { get; set; }
        public string promocode { get; set; }
        public string discount_discountItem { get; set; }
        public string discount_discountrate { get; set; }
        public string itemLine_item { get; set; }
        public string xlated_part { get; set; }
        public string final_part { get; set; }
        public Nullable<double> itemLine_quantity { get; set; }
        public string itemLine_serialNumbers { get; set; }
        public string itemLine_units { get; set; }
        public Nullable<double> itemLine_salesPrice { get; set; }
        public Nullable<double> itemLine_amount { get; set; }
        public string itemLine_description { get; set; }
        public string NetSuiteDescription { get; set; }
        public string itemLine_isTaxable { get; set; }
        public string itemLine_priceLevel { get; set; }
        public string itemLine_department { get; set; }
        public string itemLine_class { get; set; }
        public string itemLine_location { get; set; }
        public string itemLine_custom_Field_Name { get; set; }
        public string itemLine_custom_Field_Name1 { get; set; }
        public string itemLine_custom_Field_Name2 { get; set; }
        public string shipdate { get; set; }
        public string shipcarrier { get; set; }
        public string shipmethod { get; set; }
        public string shipcomplete { get; set; }
        public string shipaddresslist { get; set; }
        public string shipattention { get; set; }
        public string shipaddressee { get; set; }
        public string shipAddr1 { get; set; }
        public string shipAddr2 { get; set; }
        public string shipCity { get; set; }
        public string shipState { get; set; }
        public string shipZip { get; set; }
        public string shipCountry { get; set; }
        public string shipPhone { get; set; }
        public string terms { get; set; }
        public string billattention { get; set; }
        public string billAddressee { get; set; }
        public string billAddr1 { get; set; }
        public string billAddr2 { get; set; }
        public string billCity { get; set; }
        public string billState { get; set; }
        public string billZip { get; set; }
        public string billCountry { get; set; }
        public string billPhone { get; set; }
        public string currency { get; set; }
        public string exchangerate { get; set; }
        public string istaxable { get; set; }
        public string taxitem { get; set; }
        public string taxrate { get; set; }
        public string tobeprinted { get; set; }
        public string tobeemailed { get; set; }
        public string email { get; set; }
        public string tobefaxed { get; set; }
        public string fax { get; set; }
        public string customermessage { get; set; }
        public string custbody_nsts_ci_exclude { get; set; }
        public string custom_Field_Name { get; set; }
        public string custom_Field_Name1 { get; set; }
        public string custom_Field_Name2 { get; set; }
        public string LineSeqNo { get; set; }
        public int Id { get; set; }
    }
}
