//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SalesOrderDetail
    {
        public string SalesOrderNo { get; set; }
        public string LineKey { get; set; }
        public string LineSeqNo { get; set; }
        public string ItemCode { get; set; }
        public string ItemType { get; set; }
        public string ItemCodeDesc { get; set; }
        public string ExtendedDescriptionKey { get; set; }
        public string Discount { get; set; }
        public string Commissionable { get; set; }
        public string SubjectToExemption { get; set; }
        public string WarehouseCode { get; set; }
        public string PriceLevel { get; set; }
        public string MasterOrderLineKey { get; set; }
        public string UnitOfMeasure { get; set; }
        public string DropShip { get; set; }
        public string PrintDropShipment { get; set; }
        public string SalesKitLineKey { get; set; }
        public string CostOfGoodsSoldAcctKey { get; set; }
        public string SalesAcctKey { get; set; }
        public string PriceOverridden { get; set; }
        public string ExplodedKitItem { get; set; }
        public string StandardKitBill { get; set; }
        public string Revision { get; set; }
        public string BillOption1 { get; set; }
        public string BillOption2 { get; set; }
        public string BillOption3 { get; set; }
        public string BillOption4 { get; set; }
        public string BillOption5 { get; set; }
        public string BillOption6 { get; set; }
        public string BillOption7 { get; set; }
        public string BillOption8 { get; set; }
        public string BillOption9 { get; set; }
        public string BackorderKitCompLine { get; set; }
        public string SkipPrintCompLine { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
        public string AliasItemNo { get; set; }
        public string SOHistoryDetlSeqNo { get; set; }
        public string TaxClass { get; set; }
        public string CustomerAction { get; set; }
        public string ItemAction { get; set; }
        public string WarrantyCode { get; set; }
        public string ExpirationDate { get; set; }
        public string ExpirationOverridden { get; set; }
        public string CostOverridden { get; set; }
        public string CostCode { get; set; }
        public string CostType { get; set; }
        public string CommentText { get; set; }
        public Nullable<double> QuantityOrdered { get; set; }
        public Nullable<double> QuantityShipped { get; set; }
        public Nullable<double> QuantityBackordered { get; set; }
        public Nullable<double> MasterOriginalQty { get; set; }
        public Nullable<double> MasterQtyBalance { get; set; }
        public Nullable<double> MasterQtyOrderedToDate { get; set; }
        public Nullable<double> RepeatingQtyShippedToDate { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public Nullable<double> ExtensionAmt { get; set; }
        public Nullable<double> UnitOfMeasureConvFactor { get; set; }
        public Nullable<double> QuantityPerBill { get; set; }
        public Nullable<double> LineDiscountPercent { get; set; }
        public string Valuation { get; set; }
        public string LotSerialFullyDistributed { get; set; }
        public string APDivisionNo { get; set; }
        public string VendorNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string PurchaseOrderRequiredDate { get; set; }
        public Nullable<double> LineWeight { get; set; }
        public string CommodityCode { get; set; }
        public string AlternateTaxIdentifier { get; set; }
        public string TaxTypeApplied { get; set; }
        public string NetGrossIndicator { get; set; }
        public string DebitCreditIndicator { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public Nullable<double> TaxRate { get; set; }
    }
}
